kind: ConfigMap
apiVersion: v1
metadata:
  name: ddcheck
  namespace: default
data:
  hello.py: |-
    from checks import AgentCheck
    class HelloCheck(AgentCheck):
        def check(self, instance):
            self.gauge('hello.world', 1)
