kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-datadog-env
  namespace: default
data:
  # DD Log collection setup
  DD_LOGS_ENABLED: "true"
  # DD APM setup
  DD_APM_ENABLED: "true"
  # DD Other variables. 
  # Look for anything within BindEnv() or BindEnvAndSetDefault(), then set using DD_<config_option>
  # Reference: https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config.go#L267
  DD_LOG_LEVEL: "debug"
  DD_DOGSTATSD_SO_RCVBUF: "2048"
  DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"

  # See ds-agent:line 11>> label_to_get:My_DDAgent_xyz ==> results to ==> kube_tag:My_DDAgent_xyz
  DD_KUBERNETES_POD_LABELS_AS_TAGS: '{"label_to_get":"kube_tag","pod_status":"pod_status"}' 
  DD_KUBERNETES_POD_ANNOTATIONS_AS_TAGS: '{"anntn_to_get":"kube_antn"}'

  # To include/exclude from Metric Collection (Docker integration) and Logs Collection.
  DD_AC_EXCLUDE: "image:.*"
  DD_AC_INCLUDE: "name:datadog-agent"

  # additional host tags
  DD_TAGS: "cluster:vagrant"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-other-env
  namespace: default
data:
  MY_ENV: preprod