kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-datadog-checksd
  namespace: default
data:
  hello.py: |+
    __version__ = '1.0.0'
    # # the following try/except block will make the custom check compatible with any Agent version
    # try:
    #     # first, try to import the base class from old versions of the Agent...
    #     from checks import AgentCheck
    # except ImportError:
    #     # ...if the above failed, the check is running in Agent version 6 or later
    #     from datadog_checks.checks import AgentCheck

    # import time

    # class HelloCheck(AgentCheck):
    #     def check(self, instance):
    #       tags = instance.get('tags')
    #       self.gauge('hello.world', 1, tags=tags)
    
    # the following try/except block will make the custom check compatible with any Agent version
    try:
        # first, try to import the base class from old versions of the Agent...
        from checks import AgentCheck
    except ImportError:
        # ...if the above failed, the check is running in Agent version 6 or later
        from datadog_checks.checks import AgentCheck

    # content of the special variable __version__ will be shown in the Agent status page
    __version__ = "1.0.0"
    import datadog_agent

    class HelloCheck(AgentCheck):
        def check(self, instance):
            self.gauge('hello.world', 1)