apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo  
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: resdisport
  selector:
    name: redis
    app: demo