apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: jweb
    app: demo
    log_jweb: ""
  annotations:
    ad.datadoghq.com/web.check_names: '["http_check"]'
    ad.datadoghq.com/web.init_configs: '[{}]'
    ad.datadoghq.com/web.instances: '[{"name": "My web pod", "url": "http://%%host%%:%%port%%", timeout: 1}]'
spec:
  containers:
    - name: web
      image: janakiramm/web
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP