apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  selector:
    matchLabels:
      name: web
  replicas: 3
  template:
    metadata:
      annotations:
        ## Sample autodiscovery annotations for Datadog Agent v6
        # ad.datadoghq.com/web.check_names: '["http_check"]'
        # ad.datadoghq.com/web.init_configs: '[{}]'
        # ad.datadoghq.com/web.instances: '[{"name": "My web pod", "url": "http://%%host%%:%%port%%", timeout: 1}]'
        ## 
        ## Sample autodiscovery annotations for Datadog Agent v5
        # service-discovery.datadoghq.com/web.check_names: '["http_check"]'
        # service-discovery.datadoghq.com/web.init_configs: '[{}]'
        # service-discovery.datadoghq.com/web.instances: '[{"name": "My web pod", "url": "http://%%host%%:%%port%%", timeout: 1}]'
        ## 
      labels:
        jweb: ""
        name: web
    spec:
      containers:
        - name: nameweb
          image: janakiramm/web
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
