apiVersion: v1
kind: ReplicationController
metadata:
  namespace: development
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        jweb: jwebval
        name: web
        test_tag: test123-web
    spec:
      containers:
        - name: web
          image: janakiramm/web
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
