apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: datadog-cluster-agent
      name: datadog-agent
      annotations:
        ad.datadoghq.com/datadog-cluster-agent.check_names: '["prometheus"]'
        ad.datadoghq.com/datadog-cluster-agent.init_configs: '[{}]'
        ad.datadoghq.com/datadog-cluster-agent.instances: '[{"prometheus_url": "http://%%host%%:5000/metrics","namespace": "datadog.cluster_agent","metrics": ["go_goroutines","go_memstats_*","process_*","api_requests","datadog_requests","external_metrics"]}]'
    spec:
      serviceAccountName: dca
      containers:
      - image: datadog/cluster-agent:latest
        imagePullPolicy: Always
        name: datadog-cluster-agent
        env:
          - name: DD_API_KEY
            # value: <YOUR_API_KEY>
            valueFrom:
              secretKeyRef:
                # See secrets.yaml.example
                name: dd-secrets
                key: dd_api_key
          # Optionally reference an APP KEY for the External Metrics Provider.
          - name: DD_APP_KEY
            # value: <YOUR_API_KEY>
            valueFrom:
              secretKeyRef:
                # See secrets.yaml.example
                name: dd-secrets
                key: dd_app_key

          ## Migrated to cm-dca-env
          # - name: DD_COLLECT_KUBERNETES_EVENTS
          #   value: "true"
          # - name: DD_LEADER_ELECTION
          #   value: "true"
          # - name: DD_EXTERNAL_METRICS_PROVIDER_ENABLED
          #   value: "true"

          # - name: DD_CLUSTER_AGENT_AUTH_TOKEN
          #   value: <ThirtyX2XcharactersXlongXtoken>
          # If using a secret, you can alternatively use:
          - name: DD_CLUSTER_AGENT_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: datadog-auth-token
                key: token
          # - name: DD_CLUSTER_AGENT_AUTH_TOKEN
          #   value: '<ThirtyX2X\nha$ac!*ersXl\ngXtoken>'
        # Other environment variables from ConfigMap cm-datadog-env.yaml
        envFrom:
          - configMapRef:
              name: cm-dca-env
