apiVersion: v1
kind: Pod
metadata:
  name: counter
  annotations: 
    ad.datadoghq.com/counter.logs: |
      [{
        "source": "shell",
        "service": "foo",
        "log_processing_rules": [
          { "type": "multi_line",
            "name": "log_start_with_date",
            "pattern": "\\d{4}\\-\\d{2}\\-\\d{2}\\w\\d{2}\\:\\d{2}\\:\\d{2}\\+\\d{4}"
          }
        ]
      }]
spec:
  containers:
  - name: counter
    image: busybox:1.28
    args: [/bin/sh, -c,
            'i=0; while true; do printf "$(date -u +%Y-%m-%dT%H:%M:%S%z) - $i\nline2\nline3\nblahblah\nend\n"; i=$((i+1)); sleep 1; done']