apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: mibcd/ubuntools
    args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']
    env:
    - name: KUBELET_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    volumeMounts:
    # Other stuff
      - name: ssl-certs
        mountPath: /etc/kubernetes/ssl
  volumes:
    # Other stuff
    - name: ssl-certs
      hostPath:
        path: /etc/kubernetes/ssl
          