apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-shell
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']
      lifecycle:
        postStart:
          exec:
            command:
              - "sh"
              - "-c"
              - >
                apt update;
                apt install -y curl ngrep net-tools netcat;
      env:
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: STATSD_PORT
          value: "8125"
